create table MESSAGES (id bigint generated by default as identity, message varchar(255), primary key (id));


-- Insert 3 demo messages
INSERT INTO MESSAGES (message) VALUES ('Hallo Welt! Dies ist die erste Demo-Nachricht.');
INSERT INTO MESSAGES (message) VALUES ('Willkommen bei Quarkus mit Flyway Migration!');
INSERT INTO MESSAGES (message) VALUES ('Dies ist die dritte Testnachricht für die Datenbank.');

