create table MESSAGES (id bigint generated by default as identity, message varchar(255), primary key (id));



INSERT INTO MESSAGES (message) VALUES ('Hello World');
INSERT INTO MESSAGES (message) VALUES ('Lorem Ipsum');
